name: widgets_reflect
description: A minimal example using reflectable with Flutter.

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: any
  reflectable: any
  build_runner: any
  built_value_generator: any
  shortid: ^0.1.1
  url_launcher: ^5.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  source_gen: any

flutter:
  uses-material-design: true
